export const apiEndpoints = {
  loginWithPassowrd: "/auth/login/password",
  registerUser: "/auth/register",
  loginWithOTP: "/auth/login/otp",
  verifyOtp: "/auth/verify-otp",
  verifyAccessToken: "/auth/verify-access-token",
  verifyRefreshToken: "/auth/verify-refresh-token",
  fetchManagementUserList: "/user-actions/users-by-roles",
  fetchAllRoles: "/role-actions/roles",
  createUser: "/user-actions/users",
  updateUser: "/user-actions/users",
  logout: "/auth/logout",
  deleteUserWithId:"/user-actions/users",
  getProductList:"",
};
